[tool.ruff]
line-length = 120
target-version = "py310"
exclude = ["build", "dist", ".venv", "venv"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]  # ignore long lines (we set 120 anyway)

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
disallow_untyped_defs = false
warn_return_any = false
warn_unused_ignores = true
no_implicit_optional = false
check_untyped_defs = false

[tool.pytest.ini_options]
addopts = "-q"
