name: Bug report
description: Report a bug
body:
  - type: textarea
    attributes: { label: Description }
  - type: textarea
    attributes: { label: Steps to Reproduce }
  - type: textarea
    attributes: { label: Expected Behavior }
  - type: textarea
    attributes: { label: Logs/Traceback }
